import {confirm, input} from '@inquirer/prompts'
import {Command, Flags} from '@oclif/core'
import * as path from 'node:path'

import {JsonOutputContext} from '../../utils/json-output.js'
import {
  DEFAULT_PROOF_PRODUCTION_ROOT,
  discoverPreparedProofProductionInputs,
  prepareProofProductionInputs,
  readPreparedProofProductionInputs,
} from '../../utils/proof-release.js'

export const PROOF_RELEASE_INIT_NEXT_STEP =
  'run scrollsdk setup doge-config --proof-topology, then scrollsdk setup prep-charts'

export default class ProofReleaseInit extends Command {
  static override description =
    'Prepare production proof inputs from an extracted ProofSoftwareReleaseV1 and deployment protocol context; disabled/mock do not use this command'

  static override examples = [
    '<%= config.bin %> <%= command.id %>',
    '<%= config.bin %> <%= command.id %> --software-release /srv/releases/proof-software-release-v1.json',
    '<%= config.bin %> <%= command.id %> --software-release /srv/releases/proof-software-release-v1.json --bridge-material /srv/bridge/proof-bridge-material-v1.json',
  ]

  static override flags = {
    'bridge-material': Flags.string({
      description: 'Existing ProofBridgeMaterialV1 manifest; skips the normal CPU Bridge bake',
    }),
    'deployment-dir': Flags.string({description: 'Deployment root'}),
    'docker-platform': Flags.string({
      default: 'linux/amd64',
      description: 'Docker platform for the digest-pinned CPU Bridge baker image',
    }),
    json: Flags.boolean({default: false, description: 'Output structured JSON'}),
    'non-interactive': Flags.boolean({
      char: 'N',
      default: false,
      description: 'Run without prompts; required values must be flags, defaults, or existing state',
    }),
    'output-root': Flags.string({
      default: DEFAULT_PROOF_PRODUCTION_ROOT,
      description: 'Deployment-relative directory for copied software and baked Bridge material',
    }),
    'protocol-context': Flags.string({
      description: 'Canonical protocol_context.json generated by setup bridge-init',
    }),
    'software-release': Flags.string({
      description: 'Extracted dogeos/proof-software-release/v1 manifest',
    }),
    yes: Flags.boolean({
      char: 'y',
      default: false,
      description: 'Prepare the production inputs without the final confirmation',
    }),
  }

  public async run(): Promise<void> {
    const {flags} = await this.parse(ProofReleaseInit)
    const json = new JsonOutputContext('setup proof-release-init', flags.json)
    try {
      const nonInteractive = flags['non-interactive'] || flags.json
      const deploymentDir = path.resolve(flags['deployment-dir'] || '.')
      const existingReceipt = discoverPreparedProofProductionInputs(deploymentDir)
      const existing = existingReceipt
        ? readPreparedProofProductionInputs(existingReceipt)
        : undefined
      let softwareRelease = flags['software-release']
      if (!softwareRelease) {
        const defaultValue = existing?.softwareManifestPath
        if (nonInteractive) {
          softwareRelease = defaultValue
          if (!softwareRelease) {
            throw new Error('--software-release is required for a new non-interactive preparation')
          }
        } else {
          softwareRelease = await input({
            default: defaultValue,
            message: 'Enter the extracted dogeos/proof-software-release/v1 manifest path:',
            validate: value => value.trim() ? true : 'Software release manifest must not be empty',
          })
        }
      }

      let protocolContext = flags['protocol-context']
      if (!protocolContext) {
        const defaultValue = existing?.protocolContextPath || '.data/protocol_context.json'
        protocolContext = nonInteractive
          ? defaultValue
          : await input({
              default: defaultValue,
              message: 'Enter the canonical protocol_context.json path:',
              validate: value => value.trim() ? true : 'Protocol context path must not be empty',
            })
      }

      json.log('Production proof input plan:')
      json.log(`  Software manifest: ${path.resolve(deploymentDir, softwareRelease)}`)
      json.log(`  Protocol context:  ${path.resolve(deploymentDir, protocolContext)}`)
      json.log(`  Output root:       ${path.resolve(deploymentDir, flags['output-root'])}`)
      json.log(`  Docker platform:   ${flags['docker-platform']}`)
      if (flags['bridge-material']) {
        json.log(
          `  Bridge material:   import ${path.resolve(deploymentDir, flags['bridge-material'])}`,
        )
      } else {
        json.log('  Bridge material:   bake locally in the release-selected CPU image (no GPU)')
      }

      if (!flags.yes && !nonInteractive) {
        const proceed = await confirm({
          default: true,
          message: flags['bridge-material']
            ? 'Copy and validate these two production manifests?'
            : 'Copy the software release and bake deployment-bound Bridge material?',
        })
        if (!proceed) {
          json.log('Production proof preparation cancelled; no files were installed')
          return
        }
      }

      const prepared = await prepareProofProductionInputs({
        bridgeManifestPath: flags['bridge-material'],
        deploymentDir,
        dockerPlatform: flags['docker-platform'],
        log: message => json.log(message),
        outputRoot: flags['output-root'],
        protocolContextPath: protocolContext,
        softwareManifestPath: softwareRelease,
      })
      json.logSuccess(`Prepared production proof inputs ${prepared.release.release_id}`)
      json.logKeyValue('Software manifest', prepared.softwareManifestPath)
      json.logKeyValue('Bridge manifest', prepared.bridgeManifestPath)
      json.log(`Next: ${PROOF_RELEASE_INIT_NEXT_STEP}`)
      json.success({
        bridgeManifest: prepared.bridgeManifestPath,
        bridgeMaterialDigest: prepared.bridge.bridge_material_digest,
        nextStep: PROOF_RELEASE_INIT_NEXT_STEP,
        releaseId: prepared.release.release_id,
        resourcesRoot: prepared.resourcesRoot,
        softwareManifest: prepared.softwareManifestPath,
        softwareReleaseDigest: prepared.release.release_digest,
      })
    } catch (error) {
      json.error(
        'E718_PROOF_RELEASE_INIT_FAILED',
        error instanceof Error ? error.message : String(error),
        'CONFIGURATION',
        true,
      )
    }
  }
}
