import {confirm, input} from '@inquirer/prompts'
import {Command, Flags} from '@oclif/core'
import * as path from 'node:path'

import {JsonOutputContext} from '../../utils/json-output.js'
import {
  immutableProofImageReference,
  listPreparedProofReleaseLocks,
  prepareProofRelease,
  readPreparedProofRelease,
} from '../../utils/proof-release.js'

export const PROOF_RELEASE_INIT_NEXT_STEP =
  'run scrollsdk setup doge-config --proof-topology, then scrollsdk setup prep-charts'

export default class ProofReleaseInit extends Command {
  static override description = 'Import an immutable dogeos-core proof software release, bake deployment-bound Bridge material on CPU, and create the validated deployment lock'

  static override examples = [
    '<%= config.bin %> <%= command.id %>',
    '<%= config.bin %> <%= command.id %> --release-image dogeos69/proof-release@sha256:<digest>',
    '<%= config.bin %> <%= command.id %> --release-image dogeos69/proof-release@sha256:<digest> -N',
  ]

  static override flags = {
    'deployment-dir': Flags.string({
      description: 'Deployment root containing .data/protocol_context.json',
    }),
    json: Flags.boolean({default: false, description: 'Output structured JSON'}),
    'non-interactive': Flags.boolean({
      char: 'N',
      default: false,
      description: 'Run without prompts; --release-image is required for a new import',
    }),
    'protocol-context': Flags.string({
      description: 'Canonical protocol_context.json generated by setup bridge-init',
    }),
    'release-image': Flags.string({
      description: 'Immutable dogeos-core proof release data image (repository@sha256:...)',
    }),
    yes: Flags.boolean({
      char: 'y',
      default: false,
      description: 'Pull, validate, and bake without the final confirmation',
    }),
  }

  public async run(): Promise<void> {
    const {flags} = await this.parse(ProofReleaseInit)
    const json = new JsonOutputContext('setup proof-release-init', flags.json)
    try {
      const nonInteractive = flags['non-interactive'] || flags.json
      const deploymentDir = path.resolve(flags['deployment-dir'] || '.')
      const installedLocks = flags['release-image']
        ? []
        : listPreparedProofReleaseLocks(deploymentDir)
      const existingLock = installedLocks.length === 1 ? installedLocks[0] : undefined
      const existingImage = existingLock
        ? readPreparedProofRelease(existingLock).receipt.release_image
        : undefined
      let releaseImage = flags['release-image']
      if (releaseImage === undefined) {
        if (nonInteractive) {
          releaseImage = existingImage
          if (!releaseImage) {
            const reason = installedLocks.length > 1
              ? 'multiple releases are already prepared'
              : 'this is a new import'
            throw new Error(
              `--release-image is required in non-interactive mode because ${reason}`,
            )
          }
        } else {
          releaseImage = await input({
            default: existingImage,
            message: 'Enter the immutable dogeos-core proof release image (repository@sha256:...):',
            validate(value) {
              try {
                immutableProofImageReference(value)
                return true
              } catch (error) {
                return error instanceof Error ? error.message : String(error)
              }
            },
          })
        }
      }

      releaseImage = immutableProofImageReference(releaseImage)
      let protocolContext = flags['protocol-context']
      if (protocolContext === undefined) {
        protocolContext = nonInteractive
          ? '.data/protocol_context.json'
          : await input({
              default: '.data/protocol_context.json',
              message: 'Enter the canonical protocol_context.json path:',
            })
      }

      const resolvedProtocolContext = path.resolve(deploymentDir, protocolContext)
      json.log('Proof release preparation plan:')
      json.log(`  Immutable release: ${releaseImage}`)
      json.log(`  Protocol context:  ${resolvedProtocolContext}`)
      json.log(`  Output root:       ${path.resolve(deploymentDir, '.data/proof-releases')}`)
      json.log('  Bridge bake:       CPU-only, no GPU required')
      if (!flags.yes && !nonInteractive) {
        const proceed = await confirm({
          default: true,
          message: 'Pull this release, validate it, and bake deployment-bound Bridge material?',
        })
        if (!proceed) {
          json.log('Proof release preparation cancelled; no release directory was installed')
          return
        }
      }

      const prepared = prepareProofRelease({
        deploymentDir,
        log: message => json.log(message),
        protocolContext,
        releaseImage,
      })
      json.logSuccess(`Prepared proof release ${prepared.release.release_id}`)
      json.logKeyValue('Deployment lock', prepared.lockPath)
      json.logKeyValue('Lock digest', prepared.lock.lock_digest)
      json.log(`Next: ${PROOF_RELEASE_INIT_NEXT_STEP}`)
      json.success({
        deploymentLock: prepared.lockPath,
        deploymentLockDigest: prepared.lock.lock_digest,
        nextStep: PROOF_RELEASE_INIT_NEXT_STEP,
        releaseId: prepared.release.release_id,
        releaseImage: prepared.receipt.release_image,
        resourcesRoot: prepared.resourcesRoot,
        softwareReleaseDigest: prepared.release.release_digest,
      })
    } catch (error) {
      json.error(
        'E718_PROOF_RELEASE_INIT_FAILED',
        error instanceof Error ? error.message : String(error),
        'CONFIGURATION',
        true,
      )
    }
  }
}
