import {confirm, input, select} from '@inquirer/prompts'
import {Command, Flags} from '@oclif/core'
import * as path from 'node:path'

import {JsonOutputContext} from '../../utils/json-output.js'
import {
  immutableProofImageReference,
  listPreparedProofReleaseLocks,
  listPreparedProofSoftwareReleaseManifests,
  prepareProofRelease,
  prepareProofSoftwareRelease,
  readPreparedProofRelease,
  readPreparedProofSoftwareRelease,
} from '../../utils/proof-release.js'

export const PROOF_RELEASE_INIT_NEXT_STEP =
  'run scrollsdk setup doge-config --proof-topology, then scrollsdk setup prep-charts'

export default class ProofReleaseInit extends Command {
  static override description = 'Import an immutable dogeos-core proof release for mock mode, or explicitly prepare the complete production Bridge deployment lock'

  static override examples = [
    '<%= config.bin %> <%= command.id %>',
    '<%= config.bin %> <%= command.id %> --scope mock --release-image dogeos69/proof-release@sha256:<digest>',
    '<%= config.bin %> <%= command.id %> --scope production --release-image dogeos69/proof-release@sha256:<digest>',
  ]

  static override flags = {
    'deployment-dir': Flags.string({
      description: 'Deployment root; production scope also reads .data/protocol_context.json',
    }),
    'docker-platform': Flags.string({
      default: 'linux/amd64',
      description: 'Docker platform for the release, compiler, and CPU Bridge baker images',
    }),
    json: Flags.boolean({default: false, description: 'Output structured JSON'}),
    'non-interactive': Flags.boolean({
      char: 'N',
      default: false,
      description: 'Run without prompts; --release-image is required for a new import',
    }),
    'protocol-context': Flags.string({
      description: 'Production-only canonical protocol_context.json generated by setup bridge-init',
    }),
    'release-image': Flags.string({
      description: 'Immutable dogeos-core proof release data image (repository@sha256:...)',
    }),
    scope: Flags.string({
      description: 'Preparation scope; mock imports software/images only, production also bakes Bridge material',
      options: ['mock', 'production'],
    }),
    yes: Flags.boolean({
      char: 'y',
      default: false,
      description: 'Prepare the selected scope without the final confirmation',
    }),
  }

  public async run(): Promise<void> {
    const {flags} = await this.parse(ProofReleaseInit)
    const json = new JsonOutputContext('setup proof-release-init', flags.json)
    try {
      const nonInteractive = flags['non-interactive'] || flags.json
      const deploymentDir = path.resolve(flags['deployment-dir'] || '.')
      const scope = (flags.scope || (nonInteractive
        ? 'mock'
        : await select({
            choices: [
              {
                name: 'Mock mode (no Bridge bake or GPU; production can be prepared later)',
                value: 'mock',
              },
              {
                name: 'Production-ready (CPU Bridge bake and deployment lock)',
                value: 'production',
              },
            ],
            default: 'mock',
            message: 'Which proof mode are you preparing?',
          }))) as 'mock' | 'production'
      const installedInputs = flags['release-image']
        ? []
        : scope === 'production'
          ? listPreparedProofReleaseLocks(deploymentDir)
          : listPreparedProofSoftwareReleaseManifests(deploymentDir)
      const existingInput = installedInputs.length === 1 ? installedInputs[0] : undefined
      const existingImage = existingInput
        ? scope === 'production'
          ? readPreparedProofRelease(existingInput).receipt.release_image
          : readPreparedProofSoftwareRelease(existingInput).receipt.release_image
        : undefined
      let releaseImage = flags['release-image']
      if (releaseImage === undefined) {
        if (nonInteractive) {
          releaseImage = existingImage
          if (!releaseImage) {
            const reason = installedInputs.length > 1
              ? 'multiple releases are already prepared'
              : 'this is a new import'
            throw new Error(
              `--release-image is required in non-interactive mode because ${reason}`,
            )
          }
        } else {
          releaseImage = await input({
            default: existingImage,
            message: 'Enter the immutable dogeos-core proof release image (repository@sha256:...):',
            validate(value) {
              try {
                immutableProofImageReference(value)
                return true
              } catch (error) {
                return error instanceof Error ? error.message : String(error)
              }
            },
          })
        }
      }

      releaseImage = immutableProofImageReference(releaseImage)
      let protocolContext = flags['protocol-context']
      if (scope === 'production' && protocolContext === undefined) {
        protocolContext = nonInteractive
          ? '.data/protocol_context.json'
          : await input({
              default: '.data/protocol_context.json',
              message: 'Enter the canonical protocol_context.json path:',
            })
      }

      json.log('Proof release preparation plan:')
      json.log(`  Scope:             ${scope}`)
      json.log(`  Immutable release: ${releaseImage}`)
      if (protocolContext) {
        json.log(`  Protocol context:  ${path.resolve(deploymentDir, protocolContext)}`)
      }

      json.log(`  Output root:       ${path.resolve(deploymentDir, '.data/proof-releases')}`)
      json.log(`  Docker platform:   ${flags['docker-platform']}`)
      json.log(
        scope === 'production'
          ? '  Bridge bake:       CPU-only, no GPU required'
          : '  Bridge bake:       skipped for mock mode',
      )
      if (!flags.yes && !nonInteractive) {
        const proceed = await confirm({
          default: true,
          message: scope === 'production'
            ? 'Pull this release, validate it, and bake deployment-bound Bridge material?'
            : 'Pull and validate the immutable mock software release?',
        })
        if (!proceed) {
          json.log('Proof release preparation cancelled; no release directory was installed')
          return
        }
      }

      if (scope === 'production') {
        const prepared = await prepareProofRelease({
          deploymentDir,
          dockerPlatform: flags['docker-platform'],
          log: message => json.log(message),
          protocolContext,
          releaseImage,
        })
        json.logSuccess(`Prepared production proof release ${prepared.release.release_id}`)
        json.logKeyValue('Deployment lock', prepared.lockPath)
        json.logKeyValue('Lock digest', prepared.lock.lock_digest)
        json.log(`Next: ${PROOF_RELEASE_INIT_NEXT_STEP}`)
        json.success({
          deploymentLock: prepared.lockPath,
          deploymentLockDigest: prepared.lock.lock_digest,
          nextStep: PROOF_RELEASE_INIT_NEXT_STEP,
          releaseId: prepared.release.release_id,
          releaseImage: prepared.receipt.release_image,
          resourcesRoot: prepared.resourcesRoot,
          scope,
          softwareReleaseDigest: prepared.release.release_digest,
        })
      } else {
        const prepared = await prepareProofSoftwareRelease({
          deploymentDir,
          dockerPlatform: flags['docker-platform'],
          log: message => json.log(message),
          releaseImage,
        })
        json.logSuccess(`Prepared mock proof software release ${prepared.release.release_id}`)
        json.logKeyValue('Software manifest', prepared.manifestPath)
        json.log('Production Bridge material was not prepared; production mode remains unavailable')
        json.log(`Next: ${PROOF_RELEASE_INIT_NEXT_STEP}`)
        json.success({
          nextStep: PROOF_RELEASE_INIT_NEXT_STEP,
          releaseId: prepared.release.release_id,
          releaseImage: prepared.receipt.release_image,
          scope,
          softwareReleaseDigest: prepared.release.release_digest,
          softwareReleaseManifest: prepared.manifestPath,
        })
      }
    } catch (error) {
      json.error(
        'E718_PROOF_RELEASE_INIT_FAILED',
        error instanceof Error ? error.message : String(error),
        'CONFIGURATION',
        true,
      )
    }
  }
}
