/**
 * DeploymentSpec - Single source of truth for DogeOS deployments
 *
 * This specification is used by AI agents and deployment scripts to:
 * 1. Generate config.toml
 * 2. Generate doge-config.toml
 * 3. Generate setup_defaults.toml
 * 4. Generate values/*.yaml for Helm charts
 * 5. Validate deployment configurations
 */

export interface DeploymentSpec {
  /** Account and key configuration */
  accounts: AccountsConfig

  /** Bridge configuration */
  bridge: BridgeConfig

  /** Deprecated Celestia DA configuration retained for legacy specs only. */
  celestia?: CelestiaConfig

  /** Contract deployment configuration */
  contracts: ContractsConfig

  /** Database configuration */
  database: DatabaseConfig

  /** Dogecoin L1 configuration */
  dogecoin: DogecoinConfig

  /** Ethereum DA configuration */
  ethereumDa?: EthereumDaConfig

  /** Frontend and ingress configuration */
  frontend: FrontendConfig

  /** Genesis configuration */
  genesis: GenesisConfig

  /** Optional container image overrides for services */
  images?: ImagesConfig

  /** Infrastructure configuration */
  infrastructure: InfrastructureConfig

  /** Deployment metadata */
  metadata: DeploymentMetadata

  /** Network and chain configuration */
  network: NetworkConfig

  /** Rollup parameters */
  rollup: RollupConfig

  /** Signing configuration */
  signing: SigningConfig

  /** Optional test/development settings */
  test?: TestConfig

  /** Schema version for forward compatibility */
  version: '1.0'
}

export interface DeploymentMetadata {
  /** Optional description */
  description?: string

  /** Deployment environment: mainnet, testnet, devnet */
  environment: 'devnet' | 'mainnet' | 'testnet'

  /** Human-readable deployment name */
  name: string

  /** Optional deployment owner/contact */
  owner?: string

  /** Optional tags for organization */
  tags?: Record<string, string>
}

export interface InfrastructureConfig {
  /** AWS-specific configuration */
  aws?: {
    accountId: string
    eksClusterName: string
    region: string
    /** Secrets Manager prefix */
    secretsPrefix?: string
  }

  /** Number of bootnode instances */
  bootnodeCount: number

  /** Bootnode instance configurations (generated by gen-keystore or provided) */
  bootnodes?: BootnodeInstanceConfig[]

  /** GCP-specific configuration */
  gcp?: {
    gkeClusterName: string
    project: string
    region: string
    /** Secret Manager project (defaults to project if not set) */
    secretsProject?: string
  }

  /** Local development configuration */
  local?: {
    /** Use Kubernetes secrets directly instead of external secrets operator */
    useK8sSecrets?: boolean
  }

  /** Kubernetes namespace */
  namespace?: string

  /** Cloud provider: aws, gcp, local */
  provider: 'aws' | 'gcp' | 'local'

  /** Number of sequencer instances */
  sequencerCount: number

  /** Sequencer instance configurations (generated by gen-keystore or provided) */
  sequencers?: SequencerInstanceConfig[]
}

/** Configuration for a single sequencer instance */
export interface SequencerInstanceConfig {
  /** Enode URL for P2P peering */
  enodeUrl?: string
  /** Instance index (0, 1, 2, ...) */
  index: number
  /** Signer address derived from keystore */
  signerAddress: string
}

/** Configuration for a single bootnode instance */
export interface BootnodeInstanceConfig {
  /** Enode URL for P2P peering */
  enodeUrl?: string
  /** Instance index (0, 1, 2, ...) */
  index: number
  /** Public IP or hostname for external P2P (optional) */
  publicEndpoint?: string
}

export interface NetworkConfig {
  /** Deprecated l1-interface beacon facade endpoint retained for legacy specs only. */
  beaconRpcEndpoint?: string

  /** Deprecated DA Publisher endpoint for Celestia-backed deployments. */
  daPublisherEndpoint?: string

  /** L1 chain ID */
  l1ChainId: number

  /** L1 chain name (displayed in UIs) */
  l1ChainName: string

  /** Legacy internal l1-interface RPC endpoint (cluster-internal). */
  l1RpcEndpoint: string

  /** Internal L1 WebSocket endpoint */
  l1RpcEndpointWebsocket?: string

  /** L2 chain ID */
  l2ChainId: number

  /** L2 chain name (displayed in UIs) */
  l2ChainName: string

  /** Internal L2 RPC endpoint */
  l2RpcEndpoint: string

  /** Native token symbol */
  tokenSymbol: string
}

export interface DatabaseConfig {
  /** Database admin connection for initialization */
  admin?: {
    database: string
    host: string
    /** Use $ENV:VAR_NAME to reference environment variable */
    password: string
    port: number
    username: string
    /** VPC/internal host if different from public */
    vpcHost?: string
    vpcPort?: number
  }

  /** Database user credentials per service */
  credentials: {
    adminSystemPassword: string
    blockscoutPassword: string
    bridgeHistoryPassword: string
    chainMonitorPassword: string
    coordinatorPassword: string
    gasOraclePassword: string
    l1ExplorerPassword?: string
    rollupExplorerPassword: string
    /** Use $ENV:VAR_NAME pattern for secrets */
    rollupNodePassword: string
  }

  /** Individual service database names (auto-created) */
  databases: {
    adminSystem: string
    blockscout: string
    bridgeHistory: string
    chainMonitor: string
    coordinator: string
    gasOracle: string
    l1Explorer?: string
    rollupExplorer: string
    rollupNode: string
  }
}

export interface AccountsConfig {
  /** Deployer account (deploys all contracts) */
  deployer: {
    address: string
    /** Use $ENV:VAR_NAME for private key */
    privateKey: string
  }

  /** L1 commit sender (submits batch commitments) */
  l1CommitSender: {
    address: string
    privateKey: string
  }

  /** L1 finalize sender (finalizes batches) */
  l1FinalizeSender: {
    address: string
    privateKey: string
  }

  /** L1 gas oracle sender */
  l1GasOracleSender: {
    address: string
    privateKey: string
  }

  /** L2 gas oracle sender */
  l2GasOracleSender: {
    address: string
    privateKey: string
  }

  /** Owner account (owns upgradeable contracts) */
  owner: {
    address: string
  }
}

export interface DogecoinConfig {
  /** Optional Blockbook API for UTXO queries */
  blockbook?: {
    apiKey?: string
    apiUrl: string
  }

  /** Block height to start indexing from */
  indexerStartHeight: number

  /** Cluster-local service discovery overrides. Defaults follow stable chart service names. */
  kubernetes?: {
    blockbookPublicPort?: number
    blockbookServiceName?: string
    p2pPort?: number
    rpcPort?: number
    serviceName?: string
    zmqHashBlockPort?: number
    zmqHashTxPort?: number
    zmqRawBlockPort?: number
    zmqRawTxPort?: number
  }

  /** Network type */
  network: 'mainnet' | 'regtest' | 'testnet'

  /** RPC connection */
  rpc: {
    /** Use $ENV:VAR_NAME for password */
    password: string
    url: string
    username: string
  }

  /** Wallet file path */
  walletPath: string
}

export interface CelestiaConfig {
  /** Auth token for Celestia node */
  authToken?: string

  /** Block height to start indexing from */
  indexerStartBlock: number

  /** Mnemonic for Celestia account - use $ENV:VAR_NAME */
  mnemonic: string

  /** DA namespace (hex) */
  namespace: string

  /** Signer address for DA submissions */
  signerAddress: string

  /** Tendermint RPC URL */
  tendermintRpcUrl: string
}

export interface EthereumDaConfig {
  /** Genesis frontier used by eth_da_submitter before the first published batch. */
  batch?: {
    compression?: 'none'
    genesisBatchHash?: string
    genesisNextRelayedDepositIndex?: number
    genesisNextWithdrawIndex?: number
    genesisRelayedDepositQueueHash?: string
    genesisStateRoot?: string
    genesisWithdrawRoot?: string
    maxBlocksPerChunk?: number
    maxChunksPerBatch?: number
    maxL2GasPerChunk?: number
    maxUncompressedBatchBytesSize?: number
    minCodecVersion?: number
  }

  /** Ethereum consensus/beacon API endpoint used as the real DA source by l1-interface. */
  beaconRpcUrl?: string

  /** Ethereum DA source chain. */
  chain?: 'devnet' | 'mainnet' | 'sepolia'

  /** Real Ethereum DA execution chain ID. This is separate from DogeOS l1-interface/Dogecoin chain ID. */
  chainId?: number

  /** EIP-4844 blob confirmation/finality policy. */
  confirmationDepth?: number

  confirmerPollIntervalMs?: number

  fetchLimit?: number

  finalizationDepth?: number

  /** Real Ethereum DA execution RPC used by eth-da-submitter and L1 funding. */
  l1RpcUrl?: string

  l2Confirmations?: number

  /** DogeOS L2 execution RPC. Defaults to network.l2RpcEndpoint. */
  l2RpcUrl?: string
  lifecycleDbPath?: string
  /** Fee policy for EIP-4844 submissions. */
  maxBlobBaseFeeWei?: string
  maxFeePerGasWei?: string

  minFinality?: 'finalized' | 'pending' | 'safe'
  minPriorityFeeWei?: string
  /** eth_da_submitter lifecycle/store settings. */
  submitterDbPath?: string
}

export interface BridgeConfig {
  /** Required confirmations for deposits */
  confirmationsRequired: number

  /** Fee rate in satoshis per kvB */
  feeRateSatPerKvb: number

  /** Fee recipient address */
  feeRecipient: string

  /** Deposit and withdrawal fees in wei */
  fees: {
    deposit: string
    minWithdrawalAmount: string
    withdrawal: string
  }

  /** Key counts */
  keyCounts: {
    attestation: number
    correctness: number
    recovery: number
  }

  /** Seed string for deterministic key derivation */
  seedString: string

  /** Target funding amounts in satoshis */
  targetAmounts: {
    bridge: number
    feeWallet: number
    sequencer: number
  }

  /** Threshold settings */
  thresholds: {
    attestation: number
    correctness: number
    recovery: number
    sequencer: number
  }

  /** Timelock for recovery operations (seconds) */
  timelockSeconds: number
}

export interface SigningConfig {
  /** AWS KMS configuration */
  awsKms?: {
    accountId: string
    networkAlias: string
    region: string
    /** Key suffixes for different signers */
    suffixes: string[]
  }

  /** CubeSigner configuration */
  cubesigner?: {
    /** Role configurations from cubesigner-init */
    roles: Array<{
      keys: Array<{
        keyId: string
        keyType: string
        materialId: string
        publicKey: string
      }>
      name: string
      roleId: string
    }>
  }

  /** Local signer configuration */
  local?: {
    /** Signer instances */
    signers: Array<{
      index: number
      port: number
      /** Private key - use $ENV:VAR_NAME */
      privateKey?: string
    }>
  }

  /** Signing method */
  method: 'aws-kms' | 'cubesigner' | 'local'

  /** TSO service URL */
  tsoServiceUrl?: string
}

export interface FrontendConfig {
  /** Base domain for all services */
  baseDomain: string

  /** External URLs (for user-facing links) */
  externalUrls: {
    bridgeApi: string
    l1Explorer: string
    l1Rpc: string
    l2Explorer: string
    l2Rpc: string
    rollupScanApi: string
  }

  /** Individual service hostnames (subdomain or full domain) */
  hosts: {
    adminDashboard: string
    blockbook?: string
    blockscout: string
    blockscoutBackend?: string
    bridgeHistoryApi: string
    celestia?: string
    coordinatorApi: string
    dogecoin?: string
    frontend: string
    grafana: string
    l1Devnet?: string
    l1Explorer?: string
    rollupExplorerApi: string
    rpcGateway: string
    rpcGatewayWs?: string
    tso?: string
  }

  /** WalletConnect project ID */
  walletConnectProjectId?: string
}

export interface RollupConfig {
  /** Coordinator timing */
  coordinator: {
    batchCollectionTimeSec: number
    bundleCollectionTimeSec: number
    chunkCollectionTimeSec: number
    /** JWT secret for coordinator API - use $ENV:VAR_NAME */
    jwtSecretKey: string
  }

  /** Finalization settings */
  finalization: {
    batchDeadlineSec: number
    relayMessageDeadlineSec: number
  }

  /** Maximum batches per bundle */
  maxBatchInBundle: number

  /** Maximum blocks per chunk */
  maxBlockInChunk: number

  /** Maximum gas limit for L1 messages */
  maxL1MessageGasLimit: number

  /** Maximum transactions per chunk */
  maxTxInChunk: number

  /** Verifier digests (hex) */
  verifierDigests?: {
    digest1: string
    digest2: string
  }
}

export interface ContractsConfig {
  /** Alternative gas token settings */
  alternativeGasToken?: {
    enabled: boolean
    exchangeRateMode: 'Fixed' | 'Oracle'
    fixedExchangeRate?: string
    tokenAddress?: string
    tokenSymbolPair?: string
  }

  /** Deployment salt for deterministic addresses */
  deploymentSalt: string

  /** Gas oracle settings */
  gasOracle: {
    blobScalar: number
    penaltyFactor: number
    penaltyThreshold: number
    scalar: number
  }

  /** L1 contract deployment block (set after deployment) */
  l1DeploymentBlock?: number

  /** L1 fee vault address */
  l1FeeVaultAddr: string

  /** Contract address overrides (for reusing existing contracts) */
  overrides?: {
    l1GasPriceOracle?: string
    l1PlonkVerifier?: string
    l1Weth?: string
    l2MessageQueue?: string
    l2TxFeeVault?: string
    l2Weth?: string
    l2Whitelist?: string
  }

  /** Contract verification settings */
  verification?: {
    l1ApiKey?: string
    l1ExplorerUri: string
    l1VerifierType: 'blockscout' | 'etherscan'
    l2ApiKey?: string
    l2ExplorerUri: string
    l2VerifierType: 'blockscout' | 'etherscan'
  }
}

export interface GenesisConfig {
  /** Base fee per gas */
  baseFeePerGas: number

  /** Initial deployer balance in wei */
  deployerInitialBalance: string

  /** Maximum ETH supply on L2 */
  maxEthSupply: string
}

export interface TestConfig {
  /** Enable mock finalization (skip actual L1 finalization) */
  mockFinalizeEnabled?: boolean

  /** Mock finalization timeout in seconds */
  mockFinalizeTimeoutSec?: number

  /** Skip certain validations */
  skipValidation?: boolean
}

/**
 * Container image configuration for a single service
 */
export interface ImageConfig {
  /** Image pull policy */
  pullPolicy?: 'Always' | 'IfNotPresent' | 'Never'

  /** Container registry/repository (e.g., scrolltech/l2geth, ghcr.io/org/image) */
  repository?: string

  /** Image tag (e.g., v5.8.36, latest). Supports $ENV:VAR_NAME pattern */
  tag?: string
}

/**
 * Container images configuration for all services
 * Allows overriding default images for testing/development
 */
export interface ImagesConfig {
  /** Default settings applied to all services */
  defaults?: {
    pullPolicy?: 'Always' | 'IfNotPresent' | 'Never'
  }

  /** Per-service image overrides */
  services?: {
    blockscout?: ImageConfig
    // Bridge Services
    bridgeHistoryApi?: ImageConfig
    bridgeHistoryFetcher?: ImageConfig

    chainMonitor?: ImageConfig
    coordinator?: ImageConfig
    cubesignerSigner?: ImageConfig
    /** Deprecated Celestia DA publisher image override. */
    daPublisher?: ImageConfig
    ethDaSubmitter?: ImageConfig
    ethereumGenesisGenerator?: ImageConfig
    ethereumGeth?: ImageConfig
    ethereumLighthouse?: ImageConfig
    feeOracle?: ImageConfig
    // Frontend & Explorers
    frontends?: ImageConfig

    gasOracle?: ImageConfig
    // Infrastructure
    l1Interface?: ImageConfig
    l2Bootnode?: ImageConfig
    l2Rpc?: ImageConfig
    // L2 Execution Layer
    l2Sequencer?: ImageConfig

    rollupExplorerBackend?: ImageConfig
    // Rollup Services
    /** Deprecated in Ethereum DA mode. */
    rollupRelayer?: ImageConfig
    tsoService?: ImageConfig

    withdrawalProcessor?: ImageConfig
  }
}

/**
 * Sequencer instance configuration (generated from DeploymentSpec)
 */
export interface SequencerConfig {
  index: number
  keystore: string
  nodeKey: string
  password: string
  signerAddress: string
  staticPeers: string[]
}

/**
 * Bootnode instance configuration (generated from DeploymentSpec)
 */
export interface BootnodeConfig {
  index: number
  nodeKey: string
  publicPeers?: string[]
  staticPeers: string[]
}

/**
 * Validation result
 */
export interface ValidationResult {
  errors: ValidationError[]
  valid: boolean
  warnings: ValidationWarning[]
}

export interface ValidationError {
  code: string
  message: string
  path: string
}

export interface ValidationWarning {
  message: string
  path: string
  suggestion?: string
}
