/**
 * DeploymentSpec - Single source of truth for DogeOS deployments
 *
 * This specification is used by AI agents and deployment scripts to:
 * 1. Generate config.toml
 * 2. Generate doge-config.toml
 * 3. Generate setup_defaults.toml
 * 4. Generate protocol_seed.toml
 * 5. Generate values/*.yaml for Helm charts
 * 6. Validate deployment configurations
 */

export interface DeploymentSpec {
  /** Account and key configuration. Public owner is user-supplied; service keys are generated by setup gen-keystore. */
  accounts: AccountsConfig

  /** Bridge configuration */
  bridge: BridgeConfig

  /** Deprecated Celestia DA configuration retained for legacy specs only. */
  celestia?: CelestiaConfig

  /** Contract deployment configuration */
  contracts: ContractsConfig

  /** Database configuration */
  database: DatabaseConfig

  /** Dogecoin L1 configuration */
  dogecoin: DogecoinConfig

  /** Ethereum DA configuration */
  ethereumDa?: EthereumDaConfig

  /** Frontend and ingress configuration */
  frontend: FrontendConfig

  /** Genesis configuration */
  genesis: GenesisConfig

  /** Optional container image overrides for services */
  images?: ImagesConfig

  /** Infrastructure configuration */
  infrastructure: InfrastructureConfig

  /** Deployment metadata */
  metadata: DeploymentMetadata

  /** Network and chain configuration */
  network: NetworkConfig

  /** Rollup parameters */
  rollup: RollupConfig

  /** Signing configuration */
  signing: SigningConfig

  /** Optional test/development settings */
  test?: TestConfig

  /** Schema version for forward compatibility */
  version: '1.0'
}

export interface DeploymentMetadata {
  /** Optional description */
  description?: string

  /** Deployment environment: mainnet, testnet, devnet */
  environment: 'devnet' | 'mainnet' | 'testnet'

  /** Human-readable deployment name */
  name: string

  /** Optional deployment owner/contact */
  owner?: string

  /** Optional tags for organization */
  tags?: Record<string, string>
}

export interface InfrastructureConfig {
  /** AWS-specific configuration */
  aws?: {
    accountId: string
    eksClusterName: string
    region: string
    /** Secrets Manager prefix */
    secretsPrefix?: string
  }

  /** Number of bootnode instances */
  bootnodeCount: number

  /** Bootnode public metadata for imported/generated deployments. Most specs should only set bootnodeCount. */
  bootnodes?: BootnodeInstanceConfig[]

  /** GCP-specific configuration */
  gcp?: {
    gkeClusterName: string
    project: string
    region: string
    /** Secret Manager project (defaults to project if not set) */
    secretsProject?: string
  }

  /** Local development configuration */
  local?: {
    /** Use Kubernetes secrets directly instead of external secrets operator */
    useK8sSecrets?: boolean
  }

  /** Kubernetes namespace */
  namespace?: string

  /** Cloud provider: aws, gcp, local */
  provider: 'aws' | 'gcp' | 'local'

  /** Number of sequencer instances */
  sequencerCount: number

  /** Sequencer public metadata for imported/generated deployments. Most specs should only set sequencerCount. */
  sequencers?: SequencerInstanceConfig[]
}

/** Public metadata for a single sequencer instance. Private material is generated by setup gen-keystore. */
export interface SequencerInstanceConfig {
  /** Enode URL for P2P peering */
  enodeUrl?: string
  /** Instance index (0, 1, 2, ...) */
  index: number
  /** Signer address derived from the generated/imported sequencer keystore */
  signerAddress?: string
}

/** Public metadata for a single bootnode instance. Private nodekeys are generated by setup gen-keystore. */
export interface BootnodeInstanceConfig {
  /** Enode URL for P2P peering */
  enodeUrl?: string
  /** Instance index (0, 1, 2, ...) */
  index: number
  /** Public IP or hostname for external P2P (optional) */
  publicEndpoint?: string
}

export interface NetworkConfig {
  /** Deprecated l1-interface beacon facade endpoint retained for legacy specs only. */
  beaconRpcEndpoint?: string

  /** Deprecated DA Publisher endpoint for Celestia-backed deployments. */
  daPublisherEndpoint?: string

  /** L1 chain ID */
  l1ChainId: number

  /** L1 chain name (displayed in UIs) */
  l1ChainName: string

  /** L2 chain ID */
  l2ChainId: number

  /** L2 chain name (displayed in UIs) */
  l2ChainName: string

  /** Native token symbol */
  tokenSymbol: string
}

export interface DatabaseConfig {
  /** Database admin connection for initialization */
  admin?: {
    database: string
    host: string
    /** Use $ENV:VAR_NAME to reference environment variable */
    password: string
    port: number
    username: string
    /** VPC/internal host if different from public */
    vpcHost?: string
    vpcPort?: number
  }

  /** Database user credentials per service. Deprecated for specs; db-init should generate these. */
  credentials?: {
    adminSystemPassword: string
    blockscoutPassword: string
    bridgeHistoryPassword: string
    chainMonitorPassword: string
    coordinatorPassword: string
    gasOraclePassword: string
    l1ExplorerPassword?: string
    rollupExplorerPassword: string
    /** Use $ENV:VAR_NAME pattern for secrets */
    rollupNodePassword: string
  }

  /** @deprecated Database names are fixed by the generator and no longer need to be specified. */
  databases?: {
    adminSystem: string
    blockscout: string
    bridgeHistory: string
    chainMonitor: string
    coordinator: string
    gasOracle: string
    l1Explorer?: string
    rollupExplorer: string
    rollupNode: string
  }
}

export interface AccountsConfig {
  /** Deployer account (deploys all contracts) */
  deployer?: {
    /** Optional public address. Derived from privateKey when possible. */
    address?: string
    /** Use $ENV:VAR_NAME for private key */
    privateKey?: string
  }

  /** L1 commit sender (submits batch commitments) */
  l1CommitSender?: {
    /** Optional public address. Derived from privateKey when possible. */
    address?: string
    privateKey?: string
  }

  /** L1 finalize sender (finalizes batches) */
  l1FinalizeSender?: {
    /** Optional public address. Derived from privateKey when possible. */
    address?: string
    privateKey?: string
  }

  /** L1 gas oracle sender */
  l1GasOracleSender?: {
    /** Optional public address. Derived from privateKey when possible. */
    address?: string
    privateKey?: string
  }

  /** L2 gas oracle sender */
  l2GasOracleSender?: {
    /** Optional public address. Derived from privateKey when possible. */
    address?: string
    privateKey?: string
  }

  /** Owner account (owns upgradeable contracts) */
  owner: {
    address: string
  }
}

export interface DogecoinConfig {
  /** Optional Blockbook API for UTXO queries */
  blockbook?: {
    apiKey?: string
    apiUrl: string
  }

  /** K8s-internal Dogecoin Core RPC credentials. The internal URL is derived from network and serviceName. */
  clusterRpc?: {
    /** Use $ENV:VAR_NAME for password */
    password: string
    username: string
  }

  /** External Dogecoin RPC used by operator-side setup commands before/around deployment. */
  externalRpc?: {
    /** Use $ENV:VAR_NAME for password */
    password?: string
    url: string
    username?: string
  }

  /** Deprecated: bridge-init derives and updates this height after setup funding is known. */
  indexerStartHeight?: number

  /** Cluster-local service discovery overrides. Defaults follow stable chart service names. */
  kubernetes?: {
    blockbookPublicPort?: number
    blockbookServiceName?: string
    p2pPort?: number
    rpcPort?: number
    serviceName?: string
    zmqHashBlockPort?: number
    zmqHashTxPort?: number
    zmqRawBlockPort?: number
    zmqRawTxPort?: number
  }

  /** Dogecoin block height where the synthetic L1 chain starts using real Dogecoin block parents. */
  l1GenesisBlock?: number

  /** Network type */
  network: 'mainnet' | 'regtest' | 'testnet'

  /** @deprecated Use externalRpc for operator-side RPC and clusterRpc for K8s-internal credentials. */
  rpc?: {
    /** Use $ENV:VAR_NAME for password */
    password?: string
    url: string
    username?: string
  }

  /** Wallet file path */
  walletPath: string
}

export interface CelestiaConfig {
  /** Auth token for Celestia node */
  authToken?: string

  /** Block height to start indexing from */
  indexerStartBlock: number

  /** Mnemonic for Celestia account - use $ENV:VAR_NAME */
  mnemonic: string

  /** DA namespace (hex) */
  namespace: string

  /** Signer address for DA submissions */
  signerAddress: string

  /** Tendermint RPC URL */
  tendermintRpcUrl: string
}

export interface EthereumDaConfig {
  /** Genesis frontier used by eth_da_submitter before the first published batch. */
  batch?: {
    compression?: 'none'
    genesisBatchHash?: string
    genesisNextRelayedDepositIndex?: number
    genesisNextWithdrawIndex?: number
    genesisRelayedDepositQueueHash?: string
    genesisStateRoot?: string
    genesisWithdrawRoot?: string
    maxBlocksPerChunk?: number
    maxChunksPerBatch?: number
    maxL2GasPerChunk?: number
    maxUncompressedBatchBytesSize?: number
    minCodecVersion?: number
  }

  /** Ethereum consensus/beacon API endpoint used as the real DA source by l1-interface. */
  beaconRpcUrl?: string

  /** Ethereum DA source chain. */
  chain?: 'devnet' | 'mainnet' | 'sepolia'

  /** Real Ethereum DA execution chain ID. This is separate from DogeOS l1-interface/Dogecoin chain ID. */
  chainId?: number

  /** EIP-4844 blob confirmation/finality policy. */
  confirmationDepth?: number

  confirmerPollIntervalMs?: number

  fetchLimit?: number

  finalizationDepth?: number

  /** Real Ethereum DA execution RPC used by eth-da-submitter and L1 funding. */
  l1RpcUrl?: string

  l2Confirmations?: number

  /** DogeOS L2 execution RPC. Defaults to the fixed internal L2 RPC endpoint. */
  l2RpcUrl?: string
  lifecycleDbPath?: string
  /** Fee policy for EIP-4844 submissions. */
  maxBlobBaseFeeWei?: string
  maxFeePerGasWei?: string

  minFinality?: 'finalized' | 'pending' | 'safe'
  minPriorityFeeWei?: string
  signer?: EthereumDaSignerConfig
  /** eth_da_submitter lifecycle/store settings. */
  submitterDbPath?: string
}

export interface EthereumDaSignerConfig {
  backend?: 'aws_kms' | 'local'
  expectedAddress?: string
  kmsKeyArn?: string
  kmsKeyId?: string
  kmsRegion?: string
  namespace?: string
  serviceAccountName?: string
  serviceAccountRoleArn?: string
}

export interface BridgeConfig {
  /** Required confirmations for deposits */
  confirmationsRequired: number

  /** @deprecated Use feeRateSatsPerKvb. */
  feeRateSatPerKvb?: number

  /** Fee rate in satoshis per kvB */
  feeRateSatsPerKvb?: number

  /** Fee recipient address */
  feeRecipient: string

  /** Deposit is Dogecoin-side sats; withdrawal/min withdrawal are EVM-side wei. */
  fees: {
    /** @deprecated Use depositFeeSats. */
    deposit?: string
    depositFeeSats?: string
    /** @deprecated Use minWithdrawalAmountWei. */
    minWithdrawalAmount?: string
    minWithdrawalAmountWei?: string
    /** @deprecated Use withdrawalFeeWei. */
    withdrawal?: string
    withdrawalFeeWei?: string
  }

  /** Key counts */
  keyCounts: {
    attestation: number
    recovery: number
  }

  /** Seed string for deterministic key derivation */
  seedString: string

  /** @deprecated Use targetAmountsSats. */
  targetAmounts?: {
    bridge: number
    feeWallet: number
    sequencer: number
  }

  /** Target funding amounts in satoshis */
  targetAmountsSats?: {
    bridge: number
    feeWallet: number
    sequencer: number
  }

  /** Optional compressed TEE signer public key. If omitted, bridge setup derives one from seedString. */
  teePubkey?: string

  /** Threshold settings */
  thresholds: {
    attestation: number
    recovery: number
  }

  /** Recovery timelock placeholder or Dogecoin absolute block height */
  timelock: number
}

export interface SigningConfig {
  /** AWS KMS-backed TEE signer configuration for dummy-signers */
  awsKms?: {
    /** AWS account for the ECS/KMS TEE signer. Independent from infrastructure.aws.accountId. */
    accountId?: string
    /** ECS cluster for the ECS Express dummy signer service. Defaults to "default". */
    ecsClusterName?: string
    /** Resource name prefix for ECS/KMS TEE signer resources. Defaults to metadata.name. */
    networkAlias?: string
    /** AWS region for the ECS/KMS TEE signer. Independent from infrastructure.aws.region. */
    region?: string
  }

  /** CubeSigner attestation key configuration */
  cubesigner?: {
    /** Role configurations from cubesigner-init */
    roles?: Array<{
      keys: Array<{
        keyId: string
        keyType: string
        materialId: string
        publicKey: string
      }>
      name: string
      roleId: string
    }>
  }

  /** Local TEE signer configuration for dummy-signers */
  local?: {
    /** Signer instances */
    signers: Array<{
      index: number
      port: number
      /** Private key - use $ENV:VAR_NAME */
      privateKey?: string
    }>
  }

  /** @deprecated CubeSigner attestation and TEE signing are independent; configure cubesigner plus awsKms/local instead. */
  method?: 'aws-kms' | 'cubesigner' | 'local'

  /** TSO service URL */
  tsoServiceUrl?: string
}

export interface FrontendSubdomains {
  adminDashboard?: string
  blockbook?: string
  blockscout?: string
  blockscoutBackend?: string
  bridgeHistoryApi?: string
  celestia?: string
  coordinatorApi?: string
  dogecoin?: string
  frontend?: string
  grafana?: string
  l1Devnet?: string
  l1Explorer?: string
  rollupExplorerApi?: string
  rpcGateway?: string
  rpcGatewayWs?: string
  tso?: string
}

export interface FrontendConfig {
  /** Base domain for all services */
  baseDomain: string

  /** External URLs (for user-facing links). Omitted values are derived from protocol, baseDomain, and subdomains. */
  externalUrls: {
    adminDashboard?: string
    bridgeApi?: string
    grafana?: string
    l1Explorer?: string
    l1Rpc?: string
    l2Explorer?: string
    l2Rpc?: string
    rollupScanApi?: string
  }

  /** Individual service hostnames (subdomain or full domain) */
  hosts: {
    adminDashboard: string
    blockbook?: string
    blockscout: string
    blockscoutBackend?: string
    bridgeHistoryApi: string
    celestia?: string
    coordinatorApi: string
    dogecoin?: string
    frontend: string
    grafana: string
    l1Devnet?: string
    l1Explorer?: string
    rollupExplorerApi: string
    rpcGateway: string
    rpcGatewayWs?: string
    tso?: string
  }

  /** Public URL protocol used when deriving external URLs from hosts */
  protocol?: 'http' | 'https'

  /** Subdomain overrides used to derive hosts from baseDomain */
  subdomains?: FrontendSubdomains

  /** WalletConnect project ID */
  walletConnectProjectId?: string
}

export interface RollupConfig {
  /** Coordinator timing */
  coordinator: {
    batchCollectionTimeSec: number
    bundleCollectionTimeSec: number
    chunkCollectionTimeSec: number
    /** Deprecated for specs; setup gen-keystore generates it when absent. */
    jwtSecretKey?: string
  }

  /** Finalization settings */
  finalization: {
    batchDeadlineSec: number
    relayMessageDeadlineSec: number
  }

  /** Maximum batches per bundle */
  maxBatchInBundle: number

  /** Maximum blocks per chunk */
  maxBlockInChunk: number

  /** Maximum gas limit for L1 messages */
  maxL1MessageGasLimit: number

  /** Maximum transactions per chunk */
  maxTxInChunk: number

  /** Verifier digests (hex) */
  verifierDigests?: {
    digest1: string
    digest2: string
  }
}

export interface ContractsConfig {
  /** Alternative gas token settings */
  alternativeGasToken?: {
    enabled: boolean
    exchangeRateMode: 'Fixed' | 'Oracle'
    fixedExchangeRate?: string
    tokenAddress?: string
    tokenSymbolPair?: string
  }

  /** Deployment salt for deterministic addresses */
  deploymentSalt: string

  /** Gas oracle settings */
  gasOracle: {
    blobScalar: number
    penaltyFactor: number
    penaltyThreshold: number
    scalar: number
  }

  /** L1 contract deployment block (set after deployment) */
  l1DeploymentBlock?: number

  /** Contract address overrides (for reusing existing contracts) */
  overrides?: {
    l1GasPriceOracle?: string
    l1PlonkVerifier?: string
    l1Weth?: string
    l2MessageQueue?: string
    l2TxFeeVault?: string
    l2Wdoge?: string
    l2Whitelist?: string
  }

  /** Contract verification settings */
  verification?: {
    l1ApiKey?: string
    l1ExplorerUri: string
    l1VerifierType: 'blockscout' | 'etherscan'
    l2ApiKey?: string
    l2ExplorerUri: string
    l2VerifierType: 'blockscout' | 'etherscan'
  }
}

export interface GenesisConfig {
  /** @deprecated Use baseFeePerGasWei. */
  baseFeePerGas?: number

  /** Base fee per gas in wei */
  baseFeePerGasWei?: number

  /** @deprecated Use deployerInitialBalanceWei. */
  deployerInitialBalance?: string

  /** Initial deployer balance in wei */
  deployerInitialBalanceWei?: string

  /** @deprecated Use maxEthSupplyWei. */
  maxEthSupply?: string

  /** Maximum ETH supply on L2 in wei */
  maxEthSupplyWei?: string
}

export interface TestConfig {
  /** Enable mock finalization (skip actual L1 finalization) */
  mockFinalizeEnabled?: boolean

  /** Mock finalization timeout in seconds */
  mockFinalizeTimeoutSec?: number

  /** Skip certain validations */
  skipValidation?: boolean
}

/**
 * Container image configuration for a single service
 */
export interface ImageConfig {
  /** Image pull policy */
  pullPolicy?: 'Always' | 'IfNotPresent' | 'Never'

  /** Container registry/repository (e.g., scrolltech/l2geth, ghcr.io/org/image) */
  repository?: string

  /** Image tag (e.g., v5.8.36, latest). Supports $ENV:VAR_NAME pattern */
  tag?: string
}

/**
 * Container images configuration for all services
 * Allows overriding default images for testing/development
 */
export interface ImagesConfig {
  /** Default settings applied to all services */
  defaults?: {
    pullPolicy?: 'Always' | 'IfNotPresent' | 'Never'
  }

  /** Per-service image overrides */
  services?: {
    blockscout?: ImageConfig
    // Bridge Services
    bridgeHistoryApi?: ImageConfig
    bridgeHistoryFetcher?: ImageConfig

    chainMonitor?: ImageConfig
    coordinator?: ImageConfig
    cubesignerSigner?: ImageConfig
    /** Deprecated Celestia DA publisher image override. */
    daPublisher?: ImageConfig
    ethDaSubmitter?: ImageConfig
    ethereumGenesisGenerator?: ImageConfig
    ethereumGeth?: ImageConfig
    ethereumLighthouse?: ImageConfig
    feeOracle?: ImageConfig
    // Frontend & Explorers
    frontends?: ImageConfig

    gasOracle?: ImageConfig
    // Infrastructure
    l1Interface?: ImageConfig
    l2Bootnode?: ImageConfig
    l2Rpc?: ImageConfig
    // L2 Execution Layer
    l2Sequencer?: ImageConfig

    rollupExplorerBackend?: ImageConfig
    // Rollup Services
    /** Deprecated in Ethereum DA mode. */
    rollupRelayer?: ImageConfig
    tsoService?: ImageConfig

    withdrawalProcessor?: ImageConfig
  }
}

/**
 * Sequencer instance configuration (generated from DeploymentSpec)
 */
export interface SequencerConfig {
  index: number
  keystore: string
  nodeKey: string
  password: string
  signerAddress: string
  staticPeers: string[]
}

/**
 * Bootnode instance configuration (generated from DeploymentSpec)
 */
export interface BootnodeConfig {
  index: number
  nodeKey: string
  publicPeers?: string[]
  staticPeers: string[]
}

/**
 * Validation result
 */
export interface ValidationResult {
  errors: ValidationError[]
  valid: boolean
  warnings: ValidationWarning[]
}

export interface ValidationError {
  code: string
  message: string
  path: string
}

export interface ValidationWarning {
  message: string
  path: string
  suggestion?: string
}
