import * as fs from 'node:fs'
import * as path from 'node:path'

import { AwsCliRunner } from './aws-cli.js'

/** Default docker-compose bundle directory in the deployment working directory. */
export const PROVER_WORKER_MOCK_BUNDLE_DIR = 'prover-worker-mock/docker-compose'

export interface ProverWorkerMockBundleOptions {
  /** Public GET base for claimed-task input refs (`GET {base}/{ref.key}`). */
  artifactReadBaseUrl: string
  /** Public base URL of the proof-coordinator `/v1/prover` gateway. */
  coordinatorUrl: string
  dir?: string
  imageTag?: string
  /** Worker bearer token; must equal the coordinator's prover-worker-token. */
  workerToken: string
}

export interface ProverWorkerMockBundleResult {
  bundleDir: string
  files: string[]
}

/**
 * Read the prover-worker token from the Secrets Manager secret proof-aws-init
 * manages (`proof-work-token` + `prover-worker-token` JSON properties).
 */
export function readProverWorkerTokenFromSecretsManager(options: {
  awsProfile?: string
  awsRegion?: string
  secretName: string
}): string {
  const aws = new AwsCliRunner(options.awsProfile)
  const secretString = aws.text(
    ['secretsmanager', 'get-secret-value', '--secret-id', options.secretName],
    { query: 'SecretString', region: options.awsRegion }
  )
  const parsed = JSON.parse(secretString) as Record<string, unknown>
  if (typeof parsed !== 'object' || parsed === null) {
    throw new TypeError(`Secrets Manager secret ${options.secretName} is not a JSON property map`)
  }

  const token = parsed['prover-worker-token']
  if (typeof token !== 'string' || token.trim() === '') {
    throw new Error(`Secrets Manager secret ${options.secretName} has no prover-worker-token property`)
  }

  return token.trim()
}

const COMPOSE_YML = `# Mock prover-worker (dev/test only — deterministic, NON-cryptographic
# proofs; pairs with the mock proving topology staged by
# \`scrollsdk setup proof-config --proving-mode mock\`).
#
# Dial-out only: claims work from the proof-coordinator's /v1/prover gateway
# and fetches/uploads artifacts over HTTPS. No inbound ports needed.
name: prover-worker-mock
services:
  prover-worker:
    image: dogeos69/prover-worker-mock:\${PROVER_WORKER_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - prover-worker.env
    command:
      - prover-worker
      - --proof-coordinator-url
      - \${PROOF_COORDINATOR_URL:?set in .env or shell}
      - --artifact-read-base-url
      - \${ARTIFACT_READ_BASE_URL:?set in .env or shell}
      - --worker-id
      - ec2-mock-worker-0
      - --mode
      - mock
      - --allow-dev-mock-prover
      - --enable-prove-scroll-chunk
      - --enable-prove-scroll-batch
      - --enable-prove-bridge-transition
`

/**
 * Write the prover-worker-mock docker-compose bundle: compose file, endpoint
 * env, and the worker token env (0600 — it is a shared secret, the same
 * discipline as gen-secrets' secrets/*.env outputs). The operator syncs the
 * directory to the worker host and runs `docker compose up -d`.
 */
export function writeProverWorkerMockBundle(options: ProverWorkerMockBundleOptions): ProverWorkerMockBundleResult {
  const bundleDir = path.resolve(options.dir || PROVER_WORKER_MOCK_BUNDLE_DIR)
  fs.mkdirSync(bundleDir, { recursive: true })

  const composePath = path.join(bundleDir, 'docker-compose.yml')
  fs.writeFileSync(composePath, COMPOSE_YML)

  const envPath = path.join(bundleDir, '.env')
  fs.writeFileSync(envPath, [
    '# Generated by `scrollsdk setup proof-config --proving-mode mock`.',
    `PROOF_COORDINATOR_URL=${options.coordinatorUrl}`,
    `ARTIFACT_READ_BASE_URL=${options.artifactReadBaseUrl}`,
    ...(options.imageTag ? [`PROVER_WORKER_IMAGE_TAG=${options.imageTag}`] : []),
    '',
  ].join('\n'))

  const tokenPath = path.join(bundleDir, 'prover-worker.env')
  // writeFileSync only applies `mode` on creation; an existing world-readable
  // placeholder must not silently keep its permissions once it holds the token.
  fs.rmSync(tokenPath, { force: true })
  fs.writeFileSync(tokenPath, [
    '# Generated by `scrollsdk setup proof-config --proving-mode mock`. SECRET —',
    "# matches the coordinator's prover-worker-token (AWS Secrets Manager).",
    `DOGEOS_PROVER_WORKER_TOKEN=${options.workerToken}`,
    '',
  ].join('\n'), { mode: 0o600 })

  return { bundleDir, files: [composePath, envPath, tokenPath] }
}
