#!/bin/sh
# Deploys scroll bridge contracts to L2 geth only.
# Assumes deterministic addresses were already generated by generate-addresses.sh.
# L1 contracts are NOT deployed — l1-interface uses addresses as identifiers only.
export PS4='$(date "+%Y-%m-%dT%H:%M:%S%z") ${0##*/}:${LINENO}: '
echo "=== L2 CONTRACT DEPLOY START ==="
export FOUNDRY_EVM_VERSION="cancun"
export FOUNDRY_BYTECODE_HASH="none"
set -ex

CONFIG_FILE="./volume/config.toml"
L2_RPC_ENDPOINT="${L2_RPC_ENDPOINT}"
BATCH_SIZE="7"

echo "using L2_RPC_ENDPOINT = $L2_RPC_ENDPOINT"

SCRIPT_MODE="write-config"

# simulate L2 (dry-run against L2 geth)
echo ""
echo "simulating on L2"
forge script scripts/deterministic/DeployScroll.s.sol:DeployScroll --rpc-url "$L2_RPC_ENDPOINT" --sig "run(string,string)" "L2" "$SCRIPT_MODE" --legacy

# deploy L2 (broadcast real transactions to L2 geth)
# Note: forge may return non-zero even when all transactions succeed — it sometimes
# tries to send a post-deployment verification tx that fails with "nonce too low" or
# "replacement transaction underpriced". We capture the JSON output and check for
# the success status rather than relying on the exit code.
echo ""
echo "deploying on L2"
set +e
DEPLOY_OUTPUT=$(forge script scripts/deterministic/DeployScroll.s.sol:DeployScroll --rpc-url "$L2_RPC_ENDPOINT" --batch-size "$BATCH_SIZE" --sig "run(string,string)" "L2" "$SCRIPT_MODE" --broadcast --legacy --json 2>&1)
DEPLOY_EXIT=$?
set -e
echo "$DEPLOY_OUTPUT"

if echo "$DEPLOY_OUTPUT" | grep -q '"status":"success","transactions":'; then
  echo "=== L2 CONTRACT DEPLOY END (all transactions confirmed) ==="
elif [ $DEPLOY_EXIT -ne 0 ]; then
  echo "=== L2 CONTRACT DEPLOY FAILED ==="
  exit $DEPLOY_EXIT
fi
